services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    platform: linux/amd64
    container_name: sqlserver_db
    environment:
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=VerySecretPassword123!'
      - 'MSSQL_PID=Express'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
